# -*- coding: utf-8 -*-
"""2주차 미션

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KaELeHSbm9aY7HLeyab1IoPKtI0upzw1

📌Q1. 학생 이름과 점수를 입력하면 학점을 출력하는 학점 변환기를 만들어 봅시다.
           아래의 학점표를 토대로 만들어 주세요. [난이도 : ⭐️⭐️/5]

✔︎ 보조 설명 :

이 문제는 학생의 이름과 점수를 입력받은 뒤, 그에 해당하는 학점을 출력하는 프로그램을 만드는 것입니다.
학점은 주어진 점수 범위에 따라 부여되는데요. 예를 들어, 95점 이상부터 100점 이하인 경우에는 A+ 학점을 부여하고,
90점 이상부터 94점 이하인 경우에는 A 학점을 부여합니다.

프로그램의 출력 결과는 학생의 이름, 입력한 점수, 그리고 부여된 학점을 모두 출력해야합니다.
이를 통해 학생들은 자신의 점수에 따른 학점을 쉽게 확인할 수 있을 거에요.

프로그램을 작성할 때, 학생 이름과 점수를 받는 방법, 그리고 입력된 점수에 따라 어떤 학점을 부여할지 결정하는 방법을
구현해야 합니다. 학점 변환 규칙을 잘 이해하고 조건문(if-elif-else)을 사용하여 각 점수 범위에 해당하는 학점을 부여하는
로직을 구현해보세요. 프로그램 실행의 결과는 다음과 같은 형식으로 나와야 합니다.
"""

# minwoo

name = input("학생이름 입력: ")
grade = int(input("점수 입력: "))

print("학생이름:",name)
print("점수",grade,"점")

if grade >= 95:
    print("학점: A+")
elif grade >= 90:
    print("학점: A")
elif grade >= 85:
    print("학점: B+")
elif grade >= 80:
    print("학점: B")
elif grade >= 75:
    print("학점: C+")
elif grade >= 70:
    print("학점: C")
elif grade >= 65:
    print("학점: D+")
elif grade >= 60:
    print("학점: D")
else:
    print("학점: F")

"""📌Q2. 월급을 입력하면 연봉을 계산해주는 계산기를 만들어 봅시다.
           아래의 세율 표를 토대로 만들어 주세요. [난이도 : ⭐️⭐️/5]

✔︎ 보조 설명 :

이 문제에서는 월급을 입력하면 연봉을 계산하는 프로그램을 만들어야 합니다.
세전 연봉은 월급에 따라 계산되며, 세후 연봉은 세전 연봉에서 소득세를 제한 후 계산됩니다.

연봉 구간별 세금의 비율은 다음과 같습니다 :
- 1200만원 이하의 연봉 : 세율 6%
- 1200만원 초과 ~ 4600만원 이하의 연봉 : 세율 15%
- 4600만원 초과 ~ 8800만원 이하의 연봉 : 세율 24%
- 8800만원 초과 ~ 1억 5000만원 이하의 연봉 : 세율 35%
- 1억 5000만원 초과 ~ 3억 이하의 연봉 : 세율 38%
- 3억 초과 ~ 5억 이하의 연봉 : 40%
- 5억 초과의 연봉 : 42%

입력으로는 사용자로부터 월급을 받아들이고, 출력으로는 세전 연봉과 세후 연봉을 출력합니다.
이 때 세전 연봉은 월급을 12로 곱한 값으로 계산됩니다.
그리고 세전 연봉에 세율을 적용하여 세금을 계산한 후, 세전 연봉에서 세금을 차감한 세후 연봉을 구하면 됩니다.

예를 들어, 월급이 300만원일 경우 세전 연봉은 300*12 = 3600만원이며,
이에 6%의 세율을 적용하면 세금은 540만원입니다.
따라서 세후 연봉은 3600만원에서 540만원을 차감한 3060만원이 됩니다.

이와 같은 방식으로 세전 연봉과 세후 연봉을 계산하여 출력하는 프로그램을 작성해보세요.
프로그램 실행의 결과는 다음과 같은 형식으로 나와야 합니다.
"""

# minwoo

monthly_payment = int(input("월급 입력: "))
yearly_payment = monthly_payment*12
print("세전 연봉:",yearly_payment,"만원")
if yearly_payment <= 1200:
    tax_yearly_payment = yearly_payment - yearly_payment/100*6 # 세율 6%
    print("세후 연봉:",int(tax_yearly_payment),"만원")
elif yearly_payment <= 4600:
    tax_yearly_payment = yearly_payment - yearly_payment/100*15 # 세율 15%
    print("세후 연봉:",int(tax_yearly_payment),"만원")
elif yearly_payment <= 8800:
    tax_yearly_payment = yearly_payment - yearly_payment/100*24 # 세율 24%
    print("세후 연봉:",int(tax_yearly_payment),"만원")
elif yearly_payment <= 15000:
    tax_yearly_payment = yearly_payment - yearly_payment/100*35 # 세율 35%
    print("세후 연봉:",int(tax_yearly_payment),"만원")
elif yearly_payment <= 30000:
    tax_yearly_payment = yearly_payment - yearly_payment/100*38 # 세율 38%
    print("세후 연봉:",int(tax_yearly_payment),"만원")
elif yearly_payment <= 50000:
    tax_yearly_payment = yearly_payment - yearly_payment/100*40 # 세율 40%
    print("세후 연봉:",int(tax_yearly_payment),"만원")
else:
    tax_yearly_payment = yearly_payment - yearly_payment/100*42 # 세율 42%
    print("세후 연봉:",int(tax_yearly_payment),"만원")

"""📌Q3. 나이와 지불 방법을 입력하면, 버스 요금이 출력되는 버스 요금 계산기를 만들어봅시다.
           아래의 요금표를 토대로 만들어주세요! [난이도 : ⭐️⭐️/5]

✔︎ 보조 설명 :

이 문제는 사용자로부터 나이와 지불 방법을 입력받은 뒤, 그에 해당하는 버스 요금을 계산하여 출력하는 프로그램을 작성하는 것입니다. 나이와 지불 방법마다 요금이 다를 수 있으므로, 입력된 정보에 따라 적절한 요금을 출력해야 합니다.

프로그램을 작성할 때, 사용자로부터 나이와 지불 방법을 입력받는 방법, 그리고 입력된 정보에 따라 어떤 요금을 부여할지 경정하는 방법을 구현해야 합니다.

앞선 문제보다 조건이 1개 더 생겼으니 조금 더 복잡해지겠지요? 조건문(if-elif-else)를 적절히 활용하여 버스 요금을 계산하고 출력하는 로직을 작성해봅시다. 프로그램 실행의 결과는 다음과 같은 형식으로 나와야 합니다.
"""

# minwoo

age = (int(input("나이입력: ")))
pay = (input("카드 또는 현금입력: "))
print("나이",age,"세")

if pay=="카드":
    print("지불유형: 카드")
elif pay=="현금":
    print("지불유형: 현금")
else:
    print("카드 또는 현금을 입력하세요")

if age < 8:
    print("무료")
elif age < 14:
    if pay =="카드":
        print("버스요금: 450원")
    elif pay =="현금":
        print("버스요금: 450원")
    else:
        print("0또는 1입력")
elif age < 20:
    if pay =="카드":
        print("버스요금: 720원")
    if pay =="현금":
        print("버스요금: 1000원")
elif 20 <= age < 75:
    if pay =="카드":
        print("버스요금: 1200원")
    if pay =="현금":
        print("버스요금: 1300원")
else:
    print("무료")

"""📌 Q4. 컴퓨터와 함께하는 가위바위보 게임을 만들어봅시다!
            조건부 실행을 중심으로 만들어 보아요. [난이도 : ⭐️⭐️⭐️/5]

조건1 : 함수의 인자로는 나의 가위바위보 선택이 들어가야 합니다.
(0, 1 ,2 혹은 "가위", "바위", "보" 로 입력할 수 있습니다. - 총 6가지 방법으로 넣을 수 있음)

조건2 : 누가 무엇을 냈고, 누가 승리 했는지 출력이 되어야 합니다.

hint : 컴퓨터가 랜덤으로 가위바위보를 하도록 만드는 방법    (힌트를 보고도 잘 모르겠다면, 검색을 활용해보세요!!)

✔︎ 보조 설명 :

가위바위보 게임은 랜덤 함수를 사용하여 컴퓨터가 가위, 바위, 보 중에서 하나를 선택하고,
사용자로부터 가위, 바위, 보 중에 하나를 입력받아 두 가지 선택을 비교하여 승패를 결정하는 게임입니다.

이 문제에서는 가위, 바위, 보 중에서 하나를 입력받는 방법과 컴퓨터의 선택을 랜덤으로 생성하는 방법을 구현해야 합니다.
그리고 2개의 선택 결과를 비교하여 승패를 결정하고 결과를 출력해야 하죠.

가위바위보 게임은 다음과 같은 규칙을 따릅니다 :
- 가위는 보를 이깁니다.
- 바위는 가위를 이깁니다.
- 보는 바위를 이깁니다.

구현하는 순서는 다음과 같습니다 :
1. 컴퓨터의 선택 생성하기 - random 모듈 사용하기
2. 사용자의 선택 받기
3. 선택을 비교하고 결과 출력하기



조건이 까다로워지기에 코드도 이전 문제보다 길어지게 될 겁니다.
난이도 최상에 해당하는 문제이니, 아무 생각이 들지 않아도 너무 기죽지 마세요!

조금 더 수련하면 가위바위보 게임을 만드는 정도는 껌이 되는 순간이 찾아올 겁니다 :)
이번주에 배운 조건문(if-elif-else)를 적절히 활용하여 가위바위보 게임을 만들어보아요!
"""

# minwoo

import random
my = input("가위 또는 바위 또는 보 입력: ")
print("나:",my)
computer = random.randint(0,2)
if computer ==0:
    print("컴퓨터: 가위")
if computer ==1:
    print("컴퓨터: 바위")
if computer ==2:
    print("컴퓨터: 보")

if computer == 0:
    if my =="가위":
        print("무승부")
    if my =="바위":
        print("승리!")
    if my =="보":
        print("컴퓨터 승리!")

elif computer == 1:
    if my =="가위":
        print("컴퓨터 승리!")
    if my =="바위":
        print("무승부!")
    if my =="보":
        print("승리!")

elif computer == 2:
    if my =="가위":
        print("승리!")
    if my =="바위":
        print("컴퓨터 승리!")
    if my =="보":
        print("무승부")
else:
        print("가위 또는 바위 또는 보 입력")